//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace WindowsFormsApplication1.wsInterfaceDyn {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WSInterfaceDynamicsSoap", Namespace="http://localhost/WebService")]
    public partial class WSInterfaceDynamics : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback HelloWorldOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdDynCareersOperationCompleted;
        
        private System.Threading.SendOrPostCallback fotoOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdDynTorresSalonesOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetDatOraOperationCompleted;
        
        private System.Threading.SendOrPostCallback testConnectionOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdDynCareersPruebaOperationCompleted;
        
        private System.Threading.SendOrPostCallback ViewCareersOperationCompleted;
        
        private System.Threading.SendOrPostCallback nuevoTutorDocenteDAXOperationCompleted;
        
        private System.Threading.SendOrPostCallback nuevoEmpleadoDynamicsOperationCompleted;
        
        private System.Threading.SendOrPostCallback obtenerNombreOperationCompleted;
        
        private System.Threading.SendOrPostCallback BuscarOperationCompleted;
        
        private System.Threading.SendOrPostCallback CargarOperationCompleted;
        
        private System.Threading.SendOrPostCallback GuardarOperationCompleted;
        
        private System.Threading.SendOrPostCallback retTorresOperationCompleted;
        
        private System.Threading.SendOrPostCallback retSalonesOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WSInterfaceDynamics() {
            this.Url = global::WindowsFormsApplication1.Properties.Settings.Default.WindowsFormsApplication1_wsInterfaceDyn_WSInterfaceDynamics;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event HelloWorldCompletedEventHandler HelloWorldCompleted;
        
        /// <remarks/>
        public event UpdDynCareersCompletedEventHandler UpdDynCareersCompleted;
        
        /// <remarks/>
        public event fotoCompletedEventHandler fotoCompleted;
        
        /// <remarks/>
        public event UpdDynTorresSalonesCompletedEventHandler UpdDynTorresSalonesCompleted;
        
        /// <remarks/>
        public event GetDatOraCompletedEventHandler GetDatOraCompleted;
        
        /// <remarks/>
        public event testConnectionCompletedEventHandler testConnectionCompleted;
        
        /// <remarks/>
        public event UpdDynCareersPruebaCompletedEventHandler UpdDynCareersPruebaCompleted;
        
        /// <remarks/>
        public event ViewCareersCompletedEventHandler ViewCareersCompleted;
        
        /// <remarks/>
        public event nuevoTutorDocenteDAXCompletedEventHandler nuevoTutorDocenteDAXCompleted;
        
        /// <remarks/>
        public event nuevoEmpleadoDynamicsCompletedEventHandler nuevoEmpleadoDynamicsCompleted;
        
        /// <remarks/>
        public event obtenerNombreCompletedEventHandler obtenerNombreCompleted;
        
        /// <remarks/>
        public event BuscarCompletedEventHandler BuscarCompleted;
        
        /// <remarks/>
        public event CargarCompletedEventHandler CargarCompleted;
        
        /// <remarks/>
        public event GuardarCompletedEventHandler GuardarCompleted;
        
        /// <remarks/>
        public event retTorresCompletedEventHandler retTorresCompleted;
        
        /// <remarks/>
        public event retSalonesCompletedEventHandler retSalonesCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://localhost/WebService/HelloWorld", RequestNamespace="http://localhost/WebService", ResponseNamespace="http://localhost/WebService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string HelloWorld() {
            object[] results = this.Invoke("HelloWorld", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void HelloWorldAsync() {
            this.HelloWorldAsync(null);
        }
        
        /// <remarks/>
        public void HelloWorldAsync(object userState) {
            if ((this.HelloWorldOperationCompleted == null)) {
                this.HelloWorldOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHelloWorldOperationCompleted);
            }
            this.InvokeAsync("HelloWorld", new object[0], this.HelloWorldOperationCompleted, userState);
        }
        
        private void OnHelloWorldOperationCompleted(object arg) {
            if ((this.HelloWorldCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HelloWorldCompleted(this, new HelloWorldCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://localhost/WebService/UpdDynCareers", RequestNamespace="http://localhost/WebService", ResponseNamespace="http://localhost/WebService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string UpdDynCareers() {
            object[] results = this.Invoke("UpdDynCareers", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void UpdDynCareersAsync() {
            this.UpdDynCareersAsync(null);
        }
        
        /// <remarks/>
        public void UpdDynCareersAsync(object userState) {
            if ((this.UpdDynCareersOperationCompleted == null)) {
                this.UpdDynCareersOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdDynCareersOperationCompleted);
            }
            this.InvokeAsync("UpdDynCareers", new object[0], this.UpdDynCareersOperationCompleted, userState);
        }
        
        private void OnUpdDynCareersOperationCompleted(object arg) {
            if ((this.UpdDynCareersCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdDynCareersCompleted(this, new UpdDynCareersCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://localhost/WebService/foto", RequestNamespace="http://localhost/WebService", ResponseNamespace="http://localhost/WebService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string foto(int _correlativo) {
            object[] results = this.Invoke("foto", new object[] {
                        _correlativo});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void fotoAsync(int _correlativo) {
            this.fotoAsync(_correlativo, null);
        }
        
        /// <remarks/>
        public void fotoAsync(int _correlativo, object userState) {
            if ((this.fotoOperationCompleted == null)) {
                this.fotoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnfotoOperationCompleted);
            }
            this.InvokeAsync("foto", new object[] {
                        _correlativo}, this.fotoOperationCompleted, userState);
        }
        
        private void OnfotoOperationCompleted(object arg) {
            if ((this.fotoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.fotoCompleted(this, new fotoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://localhost/WebService/UpdDynTorresSalones", RequestNamespace="http://localhost/WebService", ResponseNamespace="http://localhost/WebService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet UpdDynTorresSalones() {
            object[] results = this.Invoke("UpdDynTorresSalones", new object[0]);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void UpdDynTorresSalonesAsync() {
            this.UpdDynTorresSalonesAsync(null);
        }
        
        /// <remarks/>
        public void UpdDynTorresSalonesAsync(object userState) {
            if ((this.UpdDynTorresSalonesOperationCompleted == null)) {
                this.UpdDynTorresSalonesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdDynTorresSalonesOperationCompleted);
            }
            this.InvokeAsync("UpdDynTorresSalones", new object[0], this.UpdDynTorresSalonesOperationCompleted, userState);
        }
        
        private void OnUpdDynTorresSalonesOperationCompleted(object arg) {
            if ((this.UpdDynTorresSalonesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdDynTorresSalonesCompleted(this, new UpdDynTorresSalonesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://localhost/WebService/GetDatOra", RequestNamespace="http://localhost/WebService", ResponseNamespace="http://localhost/WebService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetDatOra() {
            object[] results = this.Invoke("GetDatOra", new object[0]);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetDatOraAsync() {
            this.GetDatOraAsync(null);
        }
        
        /// <remarks/>
        public void GetDatOraAsync(object userState) {
            if ((this.GetDatOraOperationCompleted == null)) {
                this.GetDatOraOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDatOraOperationCompleted);
            }
            this.InvokeAsync("GetDatOra", new object[0], this.GetDatOraOperationCompleted, userState);
        }
        
        private void OnGetDatOraOperationCompleted(object arg) {
            if ((this.GetDatOraCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDatOraCompleted(this, new GetDatOraCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://localhost/WebService/testConnection", RequestNamespace="http://localhost/WebService", ResponseNamespace="http://localhost/WebService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string testConnection() {
            object[] results = this.Invoke("testConnection", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void testConnectionAsync() {
            this.testConnectionAsync(null);
        }
        
        /// <remarks/>
        public void testConnectionAsync(object userState) {
            if ((this.testConnectionOperationCompleted == null)) {
                this.testConnectionOperationCompleted = new System.Threading.SendOrPostCallback(this.OntestConnectionOperationCompleted);
            }
            this.InvokeAsync("testConnection", new object[0], this.testConnectionOperationCompleted, userState);
        }
        
        private void OntestConnectionOperationCompleted(object arg) {
            if ((this.testConnectionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.testConnectionCompleted(this, new testConnectionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://localhost/WebService/UpdDynCareersPrueba", RequestNamespace="http://localhost/WebService", ResponseNamespace="http://localhost/WebService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string UpdDynCareersPrueba(string _careerId, string _descriptionCareer, string _directorName, string _principalCareer, string _dim1, string _dim2) {
            object[] results = this.Invoke("UpdDynCareersPrueba", new object[] {
                        _careerId,
                        _descriptionCareer,
                        _directorName,
                        _principalCareer,
                        _dim1,
                        _dim2});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void UpdDynCareersPruebaAsync(string _careerId, string _descriptionCareer, string _directorName, string _principalCareer, string _dim1, string _dim2) {
            this.UpdDynCareersPruebaAsync(_careerId, _descriptionCareer, _directorName, _principalCareer, _dim1, _dim2, null);
        }
        
        /// <remarks/>
        public void UpdDynCareersPruebaAsync(string _careerId, string _descriptionCareer, string _directorName, string _principalCareer, string _dim1, string _dim2, object userState) {
            if ((this.UpdDynCareersPruebaOperationCompleted == null)) {
                this.UpdDynCareersPruebaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdDynCareersPruebaOperationCompleted);
            }
            this.InvokeAsync("UpdDynCareersPrueba", new object[] {
                        _careerId,
                        _descriptionCareer,
                        _directorName,
                        _principalCareer,
                        _dim1,
                        _dim2}, this.UpdDynCareersPruebaOperationCompleted, userState);
        }
        
        private void OnUpdDynCareersPruebaOperationCompleted(object arg) {
            if ((this.UpdDynCareersPruebaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdDynCareersPruebaCompleted(this, new UpdDynCareersPruebaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://localhost/WebService/ViewCareers", RequestNamespace="http://localhost/WebService", ResponseNamespace="http://localhost/WebService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ViewCareers() {
            object[] results = this.Invoke("ViewCareers", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ViewCareersAsync() {
            this.ViewCareersAsync(null);
        }
        
        /// <remarks/>
        public void ViewCareersAsync(object userState) {
            if ((this.ViewCareersOperationCompleted == null)) {
                this.ViewCareersOperationCompleted = new System.Threading.SendOrPostCallback(this.OnViewCareersOperationCompleted);
            }
            this.InvokeAsync("ViewCareers", new object[0], this.ViewCareersOperationCompleted, userState);
        }
        
        private void OnViewCareersOperationCompleted(object arg) {
            if ((this.ViewCareersCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ViewCareersCompleted(this, new ViewCareersCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://localhost/WebService/nuevoTutorDocenteDAX", RequestNamespace="http://localhost/WebService", ResponseNamespace="http://localhost/WebService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string nuevoTutorDocenteDAX(string _orig, string _nit, string _nombre, string _codigo) {
            object[] results = this.Invoke("nuevoTutorDocenteDAX", new object[] {
                        _orig,
                        _nit,
                        _nombre,
                        _codigo});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void nuevoTutorDocenteDAXAsync(string _orig, string _nit, string _nombre, string _codigo) {
            this.nuevoTutorDocenteDAXAsync(_orig, _nit, _nombre, _codigo, null);
        }
        
        /// <remarks/>
        public void nuevoTutorDocenteDAXAsync(string _orig, string _nit, string _nombre, string _codigo, object userState) {
            if ((this.nuevoTutorDocenteDAXOperationCompleted == null)) {
                this.nuevoTutorDocenteDAXOperationCompleted = new System.Threading.SendOrPostCallback(this.OnnuevoTutorDocenteDAXOperationCompleted);
            }
            this.InvokeAsync("nuevoTutorDocenteDAX", new object[] {
                        _orig,
                        _nit,
                        _nombre,
                        _codigo}, this.nuevoTutorDocenteDAXOperationCompleted, userState);
        }
        
        private void OnnuevoTutorDocenteDAXOperationCompleted(object arg) {
            if ((this.nuevoTutorDocenteDAXCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.nuevoTutorDocenteDAXCompleted(this, new nuevoTutorDocenteDAXCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://localhost/WebService/nuevoEmpleadoDynamics", RequestNamespace="http://localhost/WebService", ResponseNamespace="http://localhost/WebService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string nuevoEmpleadoDynamics(string _emplId, string _dpi, string _primerNombre, string _segundoNombre, string _primerApellido, string _segundoApellido, string _apellidoCasada, string _fechaNac, int _estadoCivil, int _sexo, string _paisNac, string _depNac, string _muniNac, string _depDpi, string _muniDpi) {
            object[] results = this.Invoke("nuevoEmpleadoDynamics", new object[] {
                        _emplId,
                        _dpi,
                        _primerNombre,
                        _segundoNombre,
                        _primerApellido,
                        _segundoApellido,
                        _apellidoCasada,
                        _fechaNac,
                        _estadoCivil,
                        _sexo,
                        _paisNac,
                        _depNac,
                        _muniNac,
                        _depDpi,
                        _muniDpi});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void nuevoEmpleadoDynamicsAsync(string _emplId, string _dpi, string _primerNombre, string _segundoNombre, string _primerApellido, string _segundoApellido, string _apellidoCasada, string _fechaNac, int _estadoCivil, int _sexo, string _paisNac, string _depNac, string _muniNac, string _depDpi, string _muniDpi) {
            this.nuevoEmpleadoDynamicsAsync(_emplId, _dpi, _primerNombre, _segundoNombre, _primerApellido, _segundoApellido, _apellidoCasada, _fechaNac, _estadoCivil, _sexo, _paisNac, _depNac, _muniNac, _depDpi, _muniDpi, null);
        }
        
        /// <remarks/>
        public void nuevoEmpleadoDynamicsAsync(
                    string _emplId, 
                    string _dpi, 
                    string _primerNombre, 
                    string _segundoNombre, 
                    string _primerApellido, 
                    string _segundoApellido, 
                    string _apellidoCasada, 
                    string _fechaNac, 
                    int _estadoCivil, 
                    int _sexo, 
                    string _paisNac, 
                    string _depNac, 
                    string _muniNac, 
                    string _depDpi, 
                    string _muniDpi, 
                    object userState) {
            if ((this.nuevoEmpleadoDynamicsOperationCompleted == null)) {
                this.nuevoEmpleadoDynamicsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnnuevoEmpleadoDynamicsOperationCompleted);
            }
            this.InvokeAsync("nuevoEmpleadoDynamics", new object[] {
                        _emplId,
                        _dpi,
                        _primerNombre,
                        _segundoNombre,
                        _primerApellido,
                        _segundoApellido,
                        _apellidoCasada,
                        _fechaNac,
                        _estadoCivil,
                        _sexo,
                        _paisNac,
                        _depNac,
                        _muniNac,
                        _depDpi,
                        _muniDpi}, this.nuevoEmpleadoDynamicsOperationCompleted, userState);
        }
        
        private void OnnuevoEmpleadoDynamicsOperationCompleted(object arg) {
            if ((this.nuevoEmpleadoDynamicsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.nuevoEmpleadoDynamicsCompleted(this, new nuevoEmpleadoDynamicsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://localhost/WebService/obtenerNombre", RequestNamespace="http://localhost/WebService", ResponseNamespace="http://localhost/WebService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string obtenerNombre(string _emplId) {
            object[] results = this.Invoke("obtenerNombre", new object[] {
                        _emplId});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void obtenerNombreAsync(string _emplId) {
            this.obtenerNombreAsync(_emplId, null);
        }
        
        /// <remarks/>
        public void obtenerNombreAsync(string _emplId, object userState) {
            if ((this.obtenerNombreOperationCompleted == null)) {
                this.obtenerNombreOperationCompleted = new System.Threading.SendOrPostCallback(this.OnobtenerNombreOperationCompleted);
            }
            this.InvokeAsync("obtenerNombre", new object[] {
                        _emplId}, this.obtenerNombreOperationCompleted, userState);
        }
        
        private void OnobtenerNombreOperationCompleted(object arg) {
            if ((this.obtenerNombreCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.obtenerNombreCompleted(this, new obtenerNombreCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://localhost/WebService/Buscar", RequestNamespace="http://localhost/WebService", ResponseNamespace="http://localhost/WebService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable Buscar(string _txtBusqueda) {
            object[] results = this.Invoke("Buscar", new object[] {
                        _txtBusqueda});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void BuscarAsync(string _txtBusqueda) {
            this.BuscarAsync(_txtBusqueda, null);
        }
        
        /// <remarks/>
        public void BuscarAsync(string _txtBusqueda, object userState) {
            if ((this.BuscarOperationCompleted == null)) {
                this.BuscarOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBuscarOperationCompleted);
            }
            this.InvokeAsync("Buscar", new object[] {
                        _txtBusqueda}, this.BuscarOperationCompleted, userState);
        }
        
        private void OnBuscarOperationCompleted(object arg) {
            if ((this.BuscarCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BuscarCompleted(this, new BuscarCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://localhost/WebService/Cargar", RequestNamespace="http://localhost/WebService", ResponseNamespace="http://localhost/WebService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("Nombre")]
        public string Cargar(string Codigo, out string Torre, out string Oficina, out string Extension, out string Correlativo, out string Departamento, out string Puesto) {
            object[] results = this.Invoke("Cargar", new object[] {
                        Codigo});
            Torre = ((string)(results[1]));
            Oficina = ((string)(results[2]));
            Extension = ((string)(results[3]));
            Correlativo = ((string)(results[4]));
            Departamento = ((string)(results[5]));
            Puesto = ((string)(results[6]));
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void CargarAsync(string Codigo) {
            this.CargarAsync(Codigo, null);
        }
        
        /// <remarks/>
        public void CargarAsync(string Codigo, object userState) {
            if ((this.CargarOperationCompleted == null)) {
                this.CargarOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCargarOperationCompleted);
            }
            this.InvokeAsync("Cargar", new object[] {
                        Codigo}, this.CargarOperationCompleted, userState);
        }
        
        private void OnCargarOperationCompleted(object arg) {
            if ((this.CargarCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CargarCompleted(this, new CargarCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://localhost/WebService/Guardar", RequestNamespace="http://localhost/WebService", ResponseNamespace="http://localhost/WebService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void Guardar(string Codigo, string Torre, string Oficina, string Extension) {
            this.Invoke("Guardar", new object[] {
                        Codigo,
                        Torre,
                        Oficina,
                        Extension});
        }
        
        /// <remarks/>
        public void GuardarAsync(string Codigo, string Torre, string Oficina, string Extension) {
            this.GuardarAsync(Codigo, Torre, Oficina, Extension, null);
        }
        
        /// <remarks/>
        public void GuardarAsync(string Codigo, string Torre, string Oficina, string Extension, object userState) {
            if ((this.GuardarOperationCompleted == null)) {
                this.GuardarOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGuardarOperationCompleted);
            }
            this.InvokeAsync("Guardar", new object[] {
                        Codigo,
                        Torre,
                        Oficina,
                        Extension}, this.GuardarOperationCompleted, userState);
        }
        
        private void OnGuardarOperationCompleted(object arg) {
            if ((this.GuardarCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GuardarCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://localhost/WebService/retTorres", RequestNamespace="http://localhost/WebService", ResponseNamespace="http://localhost/WebService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet retTorres() {
            object[] results = this.Invoke("retTorres", new object[0]);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void retTorresAsync() {
            this.retTorresAsync(null);
        }
        
        /// <remarks/>
        public void retTorresAsync(object userState) {
            if ((this.retTorresOperationCompleted == null)) {
                this.retTorresOperationCompleted = new System.Threading.SendOrPostCallback(this.OnretTorresOperationCompleted);
            }
            this.InvokeAsync("retTorres", new object[0], this.retTorresOperationCompleted, userState);
        }
        
        private void OnretTorresOperationCompleted(object arg) {
            if ((this.retTorresCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.retTorresCompleted(this, new retTorresCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://localhost/WebService/retSalones", RequestNamespace="http://localhost/WebService", ResponseNamespace="http://localhost/WebService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet retSalones(string _torre) {
            object[] results = this.Invoke("retSalones", new object[] {
                        _torre});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void retSalonesAsync(string _torre) {
            this.retSalonesAsync(_torre, null);
        }
        
        /// <remarks/>
        public void retSalonesAsync(string _torre, object userState) {
            if ((this.retSalonesOperationCompleted == null)) {
                this.retSalonesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnretSalonesOperationCompleted);
            }
            this.InvokeAsync("retSalones", new object[] {
                        _torre}, this.retSalonesOperationCompleted, userState);
        }
        
        private void OnretSalonesOperationCompleted(object arg) {
            if ((this.retSalonesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.retSalonesCompleted(this, new retSalonesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void HelloWorldCompletedEventHandler(object sender, HelloWorldCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HelloWorldCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HelloWorldCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void UpdDynCareersCompletedEventHandler(object sender, UpdDynCareersCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdDynCareersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdDynCareersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void fotoCompletedEventHandler(object sender, fotoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class fotoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal fotoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void UpdDynTorresSalonesCompletedEventHandler(object sender, UpdDynTorresSalonesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdDynTorresSalonesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdDynTorresSalonesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void GetDatOraCompletedEventHandler(object sender, GetDatOraCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDatOraCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetDatOraCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void testConnectionCompletedEventHandler(object sender, testConnectionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class testConnectionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal testConnectionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void UpdDynCareersPruebaCompletedEventHandler(object sender, UpdDynCareersPruebaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdDynCareersPruebaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdDynCareersPruebaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void ViewCareersCompletedEventHandler(object sender, ViewCareersCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ViewCareersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ViewCareersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void nuevoTutorDocenteDAXCompletedEventHandler(object sender, nuevoTutorDocenteDAXCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class nuevoTutorDocenteDAXCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal nuevoTutorDocenteDAXCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void nuevoEmpleadoDynamicsCompletedEventHandler(object sender, nuevoEmpleadoDynamicsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class nuevoEmpleadoDynamicsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal nuevoEmpleadoDynamicsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void obtenerNombreCompletedEventHandler(object sender, obtenerNombreCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class obtenerNombreCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal obtenerNombreCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void BuscarCompletedEventHandler(object sender, BuscarCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BuscarCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BuscarCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void CargarCompletedEventHandler(object sender, CargarCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CargarCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CargarCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string Torre {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
        
        /// <remarks/>
        public string Oficina {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[2]));
            }
        }
        
        /// <remarks/>
        public string Extension {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[3]));
            }
        }
        
        /// <remarks/>
        public string Correlativo {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[4]));
            }
        }
        
        /// <remarks/>
        public string Departamento {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[5]));
            }
        }
        
        /// <remarks/>
        public string Puesto {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[6]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void GuardarCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void retTorresCompletedEventHandler(object sender, retTorresCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class retTorresCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal retTorresCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void retSalonesCompletedEventHandler(object sender, retSalonesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class retSalonesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal retSalonesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591