//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace WindowsFormsApplication1.wsDigitalizacion {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ServiceSoap", Namespace="http://www.galileo.edu")]
    public partial class Service : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ObtenerGeneralOperationCompleted;
        
        private System.Threading.SendOrPostCallback ObtenerOperationCompleted;
        
        private System.Threading.SendOrPostCallback ObtenerxarchivoOperationCompleted;
        
        private System.Threading.SendOrPostCallback GuardarConEtiquetasOperationCompleted;
        
        private System.Threading.SendOrPostCallback GuardarGeneralOperationCompleted;
        
        private System.Threading.SendOrPostCallback GuardarGeneralFOperationCompleted;
        
        private System.Threading.SendOrPostCallback GuardarOperationCompleted;
        
        private System.Threading.SendOrPostCallback GuardarFOperationCompleted;
        
        private System.Threading.SendOrPostCallback ObtenerCarrerasxCarnetOperationCompleted;
        
        private System.Threading.SendOrPostCallback ObtieneEtiquetasxArhivoOperationCompleted;
        
        private System.Threading.SendOrPostCallback GuardarEtiquetasOperationCompleted;
        
        private System.Threading.SendOrPostCallback RemoverEtiquetasOperationCompleted;
        
        private System.Threading.SendOrPostCallback ObtenerAppsOperationCompleted;
        
        private System.Threading.SendOrPostCallback ObtenerCatOperationCompleted;
        
        private System.Threading.SendOrPostCallback ObtenerEtiquetasOperationCompleted;
        
        private System.Threading.SendOrPostCallback ObtenerArchivosOperationCompleted;
        
        private System.Threading.SendOrPostCallback DardebajaOperationCompleted;
        
        private System.Threading.SendOrPostCallback DardebajaSolOperationCompleted;
        
        private System.Threading.SendOrPostCallback AutomatizarOperationCompleted;
        
        private System.Threading.SendOrPostCallback validarOperationCompleted;
        
        private System.Threading.SendOrPostCallback obtenerTitulosxCarreraOperationCompleted;
        
        private System.Threading.SendOrPostCallback obtenerEntidadxCarreraOperationCompleted;
        
        private System.Threading.SendOrPostCallback obtenerNombreAlumnoOperationCompleted;
        
        private System.Threading.SendOrPostCallback ObtenerNombreDocenteOperationCompleted;
        
        private System.Threading.SendOrPostCallback ObtenerRequisitosCarreraOperationCompleted;
        
        private System.Threading.SendOrPostCallback ObtenerRequisitosAdmisionOperationCompleted;
        
        private System.Threading.SendOrPostCallback ObtenerEmpleadoDynamicsOperationCompleted;
        
        private System.Threading.SendOrPostCallback ObtenerFacultadesOperationCompleted;
        
        private System.Threading.SendOrPostCallback ViculosxUsuarioOperationCompleted;
        
        private System.Threading.SendOrPostCallback SolicitudesSinTerminarOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Service() {
            this.Url = global::WindowsFormsApplication1.Properties.Settings.Default.WindowsFormsApplication1_wsDigitalizacion_Service;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ObtenerGeneralCompletedEventHandler ObtenerGeneralCompleted;
        
        /// <remarks/>
        public event ObtenerCompletedEventHandler ObtenerCompleted;
        
        /// <remarks/>
        public event ObtenerxarchivoCompletedEventHandler ObtenerxarchivoCompleted;
        
        /// <remarks/>
        public event GuardarConEtiquetasCompletedEventHandler GuardarConEtiquetasCompleted;
        
        /// <remarks/>
        public event GuardarGeneralCompletedEventHandler GuardarGeneralCompleted;
        
        /// <remarks/>
        public event GuardarGeneralFCompletedEventHandler GuardarGeneralFCompleted;
        
        /// <remarks/>
        public event GuardarCompletedEventHandler GuardarCompleted;
        
        /// <remarks/>
        public event GuardarFCompletedEventHandler GuardarFCompleted;
        
        /// <remarks/>
        public event ObtenerCarrerasxCarnetCompletedEventHandler ObtenerCarrerasxCarnetCompleted;
        
        /// <remarks/>
        public event ObtieneEtiquetasxArhivoCompletedEventHandler ObtieneEtiquetasxArhivoCompleted;
        
        /// <remarks/>
        public event GuardarEtiquetasCompletedEventHandler GuardarEtiquetasCompleted;
        
        /// <remarks/>
        public event RemoverEtiquetasCompletedEventHandler RemoverEtiquetasCompleted;
        
        /// <remarks/>
        public event ObtenerAppsCompletedEventHandler ObtenerAppsCompleted;
        
        /// <remarks/>
        public event ObtenerCatCompletedEventHandler ObtenerCatCompleted;
        
        /// <remarks/>
        public event ObtenerEtiquetasCompletedEventHandler ObtenerEtiquetasCompleted;
        
        /// <remarks/>
        public event ObtenerArchivosCompletedEventHandler ObtenerArchivosCompleted;
        
        /// <remarks/>
        public event DardebajaCompletedEventHandler DardebajaCompleted;
        
        /// <remarks/>
        public event DardebajaSolCompletedEventHandler DardebajaSolCompleted;
        
        /// <remarks/>
        public event AutomatizarCompletedEventHandler AutomatizarCompleted;
        
        /// <remarks/>
        public event validarCompletedEventHandler validarCompleted;
        
        /// <remarks/>
        public event obtenerTitulosxCarreraCompletedEventHandler obtenerTitulosxCarreraCompleted;
        
        /// <remarks/>
        public event obtenerEntidadxCarreraCompletedEventHandler obtenerEntidadxCarreraCompleted;
        
        /// <remarks/>
        public event obtenerNombreAlumnoCompletedEventHandler obtenerNombreAlumnoCompleted;
        
        /// <remarks/>
        public event ObtenerNombreDocenteCompletedEventHandler ObtenerNombreDocenteCompleted;
        
        /// <remarks/>
        public event ObtenerRequisitosCarreraCompletedEventHandler ObtenerRequisitosCarreraCompleted;
        
        /// <remarks/>
        public event ObtenerRequisitosAdmisionCompletedEventHandler ObtenerRequisitosAdmisionCompleted;
        
        /// <remarks/>
        public event ObtenerEmpleadoDynamicsCompletedEventHandler ObtenerEmpleadoDynamicsCompleted;
        
        /// <remarks/>
        public event ObtenerFacultadesCompletedEventHandler ObtenerFacultadesCompleted;
        
        /// <remarks/>
        public event ViculosxUsuarioCompletedEventHandler ViculosxUsuarioCompleted;
        
        /// <remarks/>
        public event SolicitudesSinTerminarCompletedEventHandler SolicitudesSinTerminarCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.galileo.edu/ObtenerGeneral", RequestNamespace="http://www.galileo.edu", ResponseNamespace="http://www.galileo.edu", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Carchivo ObtenerGeneral(string Aplicacion, int categoria, Etiquetas[] ListaEtiquetas) {
            object[] results = this.Invoke("ObtenerGeneral", new object[] {
                        Aplicacion,
                        categoria,
                        ListaEtiquetas});
            return ((Carchivo)(results[0]));
        }
        
        /// <remarks/>
        public void ObtenerGeneralAsync(string Aplicacion, int categoria, Etiquetas[] ListaEtiquetas) {
            this.ObtenerGeneralAsync(Aplicacion, categoria, ListaEtiquetas, null);
        }
        
        /// <remarks/>
        public void ObtenerGeneralAsync(string Aplicacion, int categoria, Etiquetas[] ListaEtiquetas, object userState) {
            if ((this.ObtenerGeneralOperationCompleted == null)) {
                this.ObtenerGeneralOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObtenerGeneralOperationCompleted);
            }
            this.InvokeAsync("ObtenerGeneral", new object[] {
                        Aplicacion,
                        categoria,
                        ListaEtiquetas}, this.ObtenerGeneralOperationCompleted, userState);
        }
        
        private void OnObtenerGeneralOperationCompleted(object arg) {
            if ((this.ObtenerGeneralCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ObtenerGeneralCompleted(this, new ObtenerGeneralCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.galileo.edu/Obtener", RequestNamespace="http://www.galileo.edu", ResponseNamespace="http://www.galileo.edu", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Carchivo Obtener(string Aplicacion, int categoria, Etiquetas[] ListaEtiquetas) {
            object[] results = this.Invoke("Obtener", new object[] {
                        Aplicacion,
                        categoria,
                        ListaEtiquetas});
            return ((Carchivo)(results[0]));
        }
        
        /// <remarks/>
        public void ObtenerAsync(string Aplicacion, int categoria, Etiquetas[] ListaEtiquetas) {
            this.ObtenerAsync(Aplicacion, categoria, ListaEtiquetas, null);
        }
        
        /// <remarks/>
        public void ObtenerAsync(string Aplicacion, int categoria, Etiquetas[] ListaEtiquetas, object userState) {
            if ((this.ObtenerOperationCompleted == null)) {
                this.ObtenerOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObtenerOperationCompleted);
            }
            this.InvokeAsync("Obtener", new object[] {
                        Aplicacion,
                        categoria,
                        ListaEtiquetas}, this.ObtenerOperationCompleted, userState);
        }
        
        private void OnObtenerOperationCompleted(object arg) {
            if ((this.ObtenerCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ObtenerCompleted(this, new ObtenerCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.galileo.edu/Obtenerxarchivo", RequestNamespace="http://www.galileo.edu", ResponseNamespace="http://www.galileo.edu", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Carchivo Obtenerxarchivo(decimal idarchivo) {
            object[] results = this.Invoke("Obtenerxarchivo", new object[] {
                        idarchivo});
            return ((Carchivo)(results[0]));
        }
        
        /// <remarks/>
        public void ObtenerxarchivoAsync(decimal idarchivo) {
            this.ObtenerxarchivoAsync(idarchivo, null);
        }
        
        /// <remarks/>
        public void ObtenerxarchivoAsync(decimal idarchivo, object userState) {
            if ((this.ObtenerxarchivoOperationCompleted == null)) {
                this.ObtenerxarchivoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObtenerxarchivoOperationCompleted);
            }
            this.InvokeAsync("Obtenerxarchivo", new object[] {
                        idarchivo}, this.ObtenerxarchivoOperationCompleted, userState);
        }
        
        private void OnObtenerxarchivoOperationCompleted(object arg) {
            if ((this.ObtenerxarchivoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ObtenerxarchivoCompleted(this, new ObtenerxarchivoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.galileo.edu/GuardarConEtiquetas", RequestNamespace="http://www.galileo.edu", ResponseNamespace="http://www.galileo.edu", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void GuardarConEtiquetas(string Aplicacion, int categoria, string NombreArchivo, string tipoContenido, [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")] byte[] contenido, string usuario, Etiquetas[] ListaEtiquetas) {
            this.Invoke("GuardarConEtiquetas", new object[] {
                        Aplicacion,
                        categoria,
                        NombreArchivo,
                        tipoContenido,
                        contenido,
                        usuario,
                        ListaEtiquetas});
        }
        
        /// <remarks/>
        public void GuardarConEtiquetasAsync(string Aplicacion, int categoria, string NombreArchivo, string tipoContenido, byte[] contenido, string usuario, Etiquetas[] ListaEtiquetas) {
            this.GuardarConEtiquetasAsync(Aplicacion, categoria, NombreArchivo, tipoContenido, contenido, usuario, ListaEtiquetas, null);
        }
        
        /// <remarks/>
        public void GuardarConEtiquetasAsync(string Aplicacion, int categoria, string NombreArchivo, string tipoContenido, byte[] contenido, string usuario, Etiquetas[] ListaEtiquetas, object userState) {
            if ((this.GuardarConEtiquetasOperationCompleted == null)) {
                this.GuardarConEtiquetasOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGuardarConEtiquetasOperationCompleted);
            }
            this.InvokeAsync("GuardarConEtiquetas", new object[] {
                        Aplicacion,
                        categoria,
                        NombreArchivo,
                        tipoContenido,
                        contenido,
                        usuario,
                        ListaEtiquetas}, this.GuardarConEtiquetasOperationCompleted, userState);
        }
        
        private void OnGuardarConEtiquetasOperationCompleted(object arg) {
            if ((this.GuardarConEtiquetasCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GuardarConEtiquetasCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.galileo.edu/GuardarGeneral", RequestNamespace="http://www.galileo.edu", ResponseNamespace="http://www.galileo.edu", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void GuardarGeneral(string Aplicacion, int categoria, string NombreArchivo, string tipoContenido, [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")] byte[] contenido, string usuario, string nosol) {
            this.Invoke("GuardarGeneral", new object[] {
                        Aplicacion,
                        categoria,
                        NombreArchivo,
                        tipoContenido,
                        contenido,
                        usuario,
                        nosol});
        }
        
        /// <remarks/>
        public void GuardarGeneralAsync(string Aplicacion, int categoria, string NombreArchivo, string tipoContenido, byte[] contenido, string usuario, string nosol) {
            this.GuardarGeneralAsync(Aplicacion, categoria, NombreArchivo, tipoContenido, contenido, usuario, nosol, null);
        }
        
        /// <remarks/>
        public void GuardarGeneralAsync(string Aplicacion, int categoria, string NombreArchivo, string tipoContenido, byte[] contenido, string usuario, string nosol, object userState) {
            if ((this.GuardarGeneralOperationCompleted == null)) {
                this.GuardarGeneralOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGuardarGeneralOperationCompleted);
            }
            this.InvokeAsync("GuardarGeneral", new object[] {
                        Aplicacion,
                        categoria,
                        NombreArchivo,
                        tipoContenido,
                        contenido,
                        usuario,
                        nosol}, this.GuardarGeneralOperationCompleted, userState);
        }
        
        private void OnGuardarGeneralOperationCompleted(object arg) {
            if ((this.GuardarGeneralCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GuardarGeneralCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.galileo.edu/GuardarGeneralF", RequestNamespace="http://www.galileo.edu", ResponseNamespace="http://www.galileo.edu", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public decimal GuardarGeneralF(string Aplicacion, int categoria, string NombreArchivo, string tipoContenido, [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")] byte[] contenido, string usuario, string nosol) {
            object[] results = this.Invoke("GuardarGeneralF", new object[] {
                        Aplicacion,
                        categoria,
                        NombreArchivo,
                        tipoContenido,
                        contenido,
                        usuario,
                        nosol});
            return ((decimal)(results[0]));
        }
        
        /// <remarks/>
        public void GuardarGeneralFAsync(string Aplicacion, int categoria, string NombreArchivo, string tipoContenido, byte[] contenido, string usuario, string nosol) {
            this.GuardarGeneralFAsync(Aplicacion, categoria, NombreArchivo, tipoContenido, contenido, usuario, nosol, null);
        }
        
        /// <remarks/>
        public void GuardarGeneralFAsync(string Aplicacion, int categoria, string NombreArchivo, string tipoContenido, byte[] contenido, string usuario, string nosol, object userState) {
            if ((this.GuardarGeneralFOperationCompleted == null)) {
                this.GuardarGeneralFOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGuardarGeneralFOperationCompleted);
            }
            this.InvokeAsync("GuardarGeneralF", new object[] {
                        Aplicacion,
                        categoria,
                        NombreArchivo,
                        tipoContenido,
                        contenido,
                        usuario,
                        nosol}, this.GuardarGeneralFOperationCompleted, userState);
        }
        
        private void OnGuardarGeneralFOperationCompleted(object arg) {
            if ((this.GuardarGeneralFCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GuardarGeneralFCompleted(this, new GuardarGeneralFCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.galileo.edu/Guardar", RequestNamespace="http://www.galileo.edu", ResponseNamespace="http://www.galileo.edu", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void Guardar(string Aplicacion, int categoria, string NombreArchivo, string tipoContenido, [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")] byte[] contenido, string usuario) {
            this.Invoke("Guardar", new object[] {
                        Aplicacion,
                        categoria,
                        NombreArchivo,
                        tipoContenido,
                        contenido,
                        usuario});
        }
        
        /// <remarks/>
        public void GuardarAsync(string Aplicacion, int categoria, string NombreArchivo, string tipoContenido, byte[] contenido, string usuario) {
            this.GuardarAsync(Aplicacion, categoria, NombreArchivo, tipoContenido, contenido, usuario, null);
        }
        
        /// <remarks/>
        public void GuardarAsync(string Aplicacion, int categoria, string NombreArchivo, string tipoContenido, byte[] contenido, string usuario, object userState) {
            if ((this.GuardarOperationCompleted == null)) {
                this.GuardarOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGuardarOperationCompleted);
            }
            this.InvokeAsync("Guardar", new object[] {
                        Aplicacion,
                        categoria,
                        NombreArchivo,
                        tipoContenido,
                        contenido,
                        usuario}, this.GuardarOperationCompleted, userState);
        }
        
        private void OnGuardarOperationCompleted(object arg) {
            if ((this.GuardarCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GuardarCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.galileo.edu/GuardarF", RequestNamespace="http://www.galileo.edu", ResponseNamespace="http://www.galileo.edu", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public decimal GuardarF(string Aplicacion, int categoria, string NombreArchivo, string tipoContenido, [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")] byte[] contenido, string usuario) {
            object[] results = this.Invoke("GuardarF", new object[] {
                        Aplicacion,
                        categoria,
                        NombreArchivo,
                        tipoContenido,
                        contenido,
                        usuario});
            return ((decimal)(results[0]));
        }
        
        /// <remarks/>
        public void GuardarFAsync(string Aplicacion, int categoria, string NombreArchivo, string tipoContenido, byte[] contenido, string usuario) {
            this.GuardarFAsync(Aplicacion, categoria, NombreArchivo, tipoContenido, contenido, usuario, null);
        }
        
        /// <remarks/>
        public void GuardarFAsync(string Aplicacion, int categoria, string NombreArchivo, string tipoContenido, byte[] contenido, string usuario, object userState) {
            if ((this.GuardarFOperationCompleted == null)) {
                this.GuardarFOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGuardarFOperationCompleted);
            }
            this.InvokeAsync("GuardarF", new object[] {
                        Aplicacion,
                        categoria,
                        NombreArchivo,
                        tipoContenido,
                        contenido,
                        usuario}, this.GuardarFOperationCompleted, userState);
        }
        
        private void OnGuardarFOperationCompleted(object arg) {
            if ((this.GuardarFCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GuardarFCompleted(this, new GuardarFCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.galileo.edu/ObtenerCarrerasxCarnet", RequestNamespace="http://www.galileo.edu", ResponseNamespace="http://www.galileo.edu", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet ObtenerCarrerasxCarnet(string carnet) {
            object[] results = this.Invoke("ObtenerCarrerasxCarnet", new object[] {
                        carnet});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void ObtenerCarrerasxCarnetAsync(string carnet) {
            this.ObtenerCarrerasxCarnetAsync(carnet, null);
        }
        
        /// <remarks/>
        public void ObtenerCarrerasxCarnetAsync(string carnet, object userState) {
            if ((this.ObtenerCarrerasxCarnetOperationCompleted == null)) {
                this.ObtenerCarrerasxCarnetOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObtenerCarrerasxCarnetOperationCompleted);
            }
            this.InvokeAsync("ObtenerCarrerasxCarnet", new object[] {
                        carnet}, this.ObtenerCarrerasxCarnetOperationCompleted, userState);
        }
        
        private void OnObtenerCarrerasxCarnetOperationCompleted(object arg) {
            if ((this.ObtenerCarrerasxCarnetCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ObtenerCarrerasxCarnetCompleted(this, new ObtenerCarrerasxCarnetCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.galileo.edu/ObtieneEtiquetasxArhivo", RequestNamespace="http://www.galileo.edu", ResponseNamespace="http://www.galileo.edu", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet ObtieneEtiquetasxArhivo(decimal idarchivo) {
            object[] results = this.Invoke("ObtieneEtiquetasxArhivo", new object[] {
                        idarchivo});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void ObtieneEtiquetasxArhivoAsync(decimal idarchivo) {
            this.ObtieneEtiquetasxArhivoAsync(idarchivo, null);
        }
        
        /// <remarks/>
        public void ObtieneEtiquetasxArhivoAsync(decimal idarchivo, object userState) {
            if ((this.ObtieneEtiquetasxArhivoOperationCompleted == null)) {
                this.ObtieneEtiquetasxArhivoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObtieneEtiquetasxArhivoOperationCompleted);
            }
            this.InvokeAsync("ObtieneEtiquetasxArhivo", new object[] {
                        idarchivo}, this.ObtieneEtiquetasxArhivoOperationCompleted, userState);
        }
        
        private void OnObtieneEtiquetasxArhivoOperationCompleted(object arg) {
            if ((this.ObtieneEtiquetasxArhivoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ObtieneEtiquetasxArhivoCompleted(this, new ObtieneEtiquetasxArhivoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.galileo.edu/GuardarEtiquetas", RequestNamespace="http://www.galileo.edu", ResponseNamespace="http://www.galileo.edu", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void GuardarEtiquetas(decimal idarchivo, string Aplicacion, int categoria, Etiquetas[] ListaEtiquetas) {
            this.Invoke("GuardarEtiquetas", new object[] {
                        idarchivo,
                        Aplicacion,
                        categoria,
                        ListaEtiquetas});
        }
        
        /// <remarks/>
        public void GuardarEtiquetasAsync(decimal idarchivo, string Aplicacion, int categoria, Etiquetas[] ListaEtiquetas) {
            this.GuardarEtiquetasAsync(idarchivo, Aplicacion, categoria, ListaEtiquetas, null);
        }
        
        /// <remarks/>
        public void GuardarEtiquetasAsync(decimal idarchivo, string Aplicacion, int categoria, Etiquetas[] ListaEtiquetas, object userState) {
            if ((this.GuardarEtiquetasOperationCompleted == null)) {
                this.GuardarEtiquetasOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGuardarEtiquetasOperationCompleted);
            }
            this.InvokeAsync("GuardarEtiquetas", new object[] {
                        idarchivo,
                        Aplicacion,
                        categoria,
                        ListaEtiquetas}, this.GuardarEtiquetasOperationCompleted, userState);
        }
        
        private void OnGuardarEtiquetasOperationCompleted(object arg) {
            if ((this.GuardarEtiquetasCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GuardarEtiquetasCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.galileo.edu/RemoverEtiquetas", RequestNamespace="http://www.galileo.edu", ResponseNamespace="http://www.galileo.edu", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void RemoverEtiquetas(decimal idarchivo, string Aplicacion, int categoria, Etiquetas[] ListaEtiquetas) {
            this.Invoke("RemoverEtiquetas", new object[] {
                        idarchivo,
                        Aplicacion,
                        categoria,
                        ListaEtiquetas});
        }
        
        /// <remarks/>
        public void RemoverEtiquetasAsync(decimal idarchivo, string Aplicacion, int categoria, Etiquetas[] ListaEtiquetas) {
            this.RemoverEtiquetasAsync(idarchivo, Aplicacion, categoria, ListaEtiquetas, null);
        }
        
        /// <remarks/>
        public void RemoverEtiquetasAsync(decimal idarchivo, string Aplicacion, int categoria, Etiquetas[] ListaEtiquetas, object userState) {
            if ((this.RemoverEtiquetasOperationCompleted == null)) {
                this.RemoverEtiquetasOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRemoverEtiquetasOperationCompleted);
            }
            this.InvokeAsync("RemoverEtiquetas", new object[] {
                        idarchivo,
                        Aplicacion,
                        categoria,
                        ListaEtiquetas}, this.RemoverEtiquetasOperationCompleted, userState);
        }
        
        private void OnRemoverEtiquetasOperationCompleted(object arg) {
            if ((this.RemoverEtiquetasCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RemoverEtiquetasCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.galileo.edu/ObtenerApps", RequestNamespace="http://www.galileo.edu", ResponseNamespace="http://www.galileo.edu", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet ObtenerApps() {
            object[] results = this.Invoke("ObtenerApps", new object[0]);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void ObtenerAppsAsync() {
            this.ObtenerAppsAsync(null);
        }
        
        /// <remarks/>
        public void ObtenerAppsAsync(object userState) {
            if ((this.ObtenerAppsOperationCompleted == null)) {
                this.ObtenerAppsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObtenerAppsOperationCompleted);
            }
            this.InvokeAsync("ObtenerApps", new object[0], this.ObtenerAppsOperationCompleted, userState);
        }
        
        private void OnObtenerAppsOperationCompleted(object arg) {
            if ((this.ObtenerAppsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ObtenerAppsCompleted(this, new ObtenerAppsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.galileo.edu/ObtenerCat", RequestNamespace="http://www.galileo.edu", ResponseNamespace="http://www.galileo.edu", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet ObtenerCat(string Aplicacion) {
            object[] results = this.Invoke("ObtenerCat", new object[] {
                        Aplicacion});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void ObtenerCatAsync(string Aplicacion) {
            this.ObtenerCatAsync(Aplicacion, null);
        }
        
        /// <remarks/>
        public void ObtenerCatAsync(string Aplicacion, object userState) {
            if ((this.ObtenerCatOperationCompleted == null)) {
                this.ObtenerCatOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObtenerCatOperationCompleted);
            }
            this.InvokeAsync("ObtenerCat", new object[] {
                        Aplicacion}, this.ObtenerCatOperationCompleted, userState);
        }
        
        private void OnObtenerCatOperationCompleted(object arg) {
            if ((this.ObtenerCatCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ObtenerCatCompleted(this, new ObtenerCatCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.galileo.edu/ObtenerEtiquetas", RequestNamespace="http://www.galileo.edu", ResponseNamespace="http://www.galileo.edu", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet ObtenerEtiquetas() {
            object[] results = this.Invoke("ObtenerEtiquetas", new object[0]);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void ObtenerEtiquetasAsync() {
            this.ObtenerEtiquetasAsync(null);
        }
        
        /// <remarks/>
        public void ObtenerEtiquetasAsync(object userState) {
            if ((this.ObtenerEtiquetasOperationCompleted == null)) {
                this.ObtenerEtiquetasOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObtenerEtiquetasOperationCompleted);
            }
            this.InvokeAsync("ObtenerEtiquetas", new object[0], this.ObtenerEtiquetasOperationCompleted, userState);
        }
        
        private void OnObtenerEtiquetasOperationCompleted(object arg) {
            if ((this.ObtenerEtiquetasCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ObtenerEtiquetasCompleted(this, new ObtenerEtiquetasCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.galileo.edu/ObtenerArchivos", RequestNamespace="http://www.galileo.edu", ResponseNamespace="http://www.galileo.edu", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet ObtenerArchivos(string Aplicacion, int categoria, Etiquetas[] ListaEtiquetas) {
            object[] results = this.Invoke("ObtenerArchivos", new object[] {
                        Aplicacion,
                        categoria,
                        ListaEtiquetas});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void ObtenerArchivosAsync(string Aplicacion, int categoria, Etiquetas[] ListaEtiquetas) {
            this.ObtenerArchivosAsync(Aplicacion, categoria, ListaEtiquetas, null);
        }
        
        /// <remarks/>
        public void ObtenerArchivosAsync(string Aplicacion, int categoria, Etiquetas[] ListaEtiquetas, object userState) {
            if ((this.ObtenerArchivosOperationCompleted == null)) {
                this.ObtenerArchivosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObtenerArchivosOperationCompleted);
            }
            this.InvokeAsync("ObtenerArchivos", new object[] {
                        Aplicacion,
                        categoria,
                        ListaEtiquetas}, this.ObtenerArchivosOperationCompleted, userState);
        }
        
        private void OnObtenerArchivosOperationCompleted(object arg) {
            if ((this.ObtenerArchivosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ObtenerArchivosCompleted(this, new ObtenerArchivosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.galileo.edu/Dardebaja", RequestNamespace="http://www.galileo.edu", ResponseNamespace="http://www.galileo.edu", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void Dardebaja(decimal idarchivo) {
            this.Invoke("Dardebaja", new object[] {
                        idarchivo});
        }
        
        /// <remarks/>
        public void DardebajaAsync(decimal idarchivo) {
            this.DardebajaAsync(idarchivo, null);
        }
        
        /// <remarks/>
        public void DardebajaAsync(decimal idarchivo, object userState) {
            if ((this.DardebajaOperationCompleted == null)) {
                this.DardebajaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDardebajaOperationCompleted);
            }
            this.InvokeAsync("Dardebaja", new object[] {
                        idarchivo}, this.DardebajaOperationCompleted, userState);
        }
        
        private void OnDardebajaOperationCompleted(object arg) {
            if ((this.DardebajaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DardebajaCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.galileo.edu/DardebajaSol", RequestNamespace="http://www.galileo.edu", ResponseNamespace="http://www.galileo.edu", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void DardebajaSol(decimal idarchivo, string nosol) {
            this.Invoke("DardebajaSol", new object[] {
                        idarchivo,
                        nosol});
        }
        
        /// <remarks/>
        public void DardebajaSolAsync(decimal idarchivo, string nosol) {
            this.DardebajaSolAsync(idarchivo, nosol, null);
        }
        
        /// <remarks/>
        public void DardebajaSolAsync(decimal idarchivo, string nosol, object userState) {
            if ((this.DardebajaSolOperationCompleted == null)) {
                this.DardebajaSolOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDardebajaSolOperationCompleted);
            }
            this.InvokeAsync("DardebajaSol", new object[] {
                        idarchivo,
                        nosol}, this.DardebajaSolOperationCompleted, userState);
        }
        
        private void OnDardebajaSolOperationCompleted(object arg) {
            if ((this.DardebajaSolCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DardebajaSolCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.galileo.edu/Automatizar", RequestNamespace="http://www.galileo.edu", ResponseNamespace="http://www.galileo.edu", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void Automatizar(decimal idarchivo) {
            this.Invoke("Automatizar", new object[] {
                        idarchivo});
        }
        
        /// <remarks/>
        public void AutomatizarAsync(decimal idarchivo) {
            this.AutomatizarAsync(idarchivo, null);
        }
        
        /// <remarks/>
        public void AutomatizarAsync(decimal idarchivo, object userState) {
            if ((this.AutomatizarOperationCompleted == null)) {
                this.AutomatizarOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAutomatizarOperationCompleted);
            }
            this.InvokeAsync("Automatizar", new object[] {
                        idarchivo}, this.AutomatizarOperationCompleted, userState);
        }
        
        private void OnAutomatizarOperationCompleted(object arg) {
            if ((this.AutomatizarCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AutomatizarCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.galileo.edu/validar", RequestNamespace="http://www.galileo.edu", ResponseNamespace="http://www.galileo.edu", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool validar(string usuario, string password) {
            object[] results = this.Invoke("validar", new object[] {
                        usuario,
                        password});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void validarAsync(string usuario, string password) {
            this.validarAsync(usuario, password, null);
        }
        
        /// <remarks/>
        public void validarAsync(string usuario, string password, object userState) {
            if ((this.validarOperationCompleted == null)) {
                this.validarOperationCompleted = new System.Threading.SendOrPostCallback(this.OnvalidarOperationCompleted);
            }
            this.InvokeAsync("validar", new object[] {
                        usuario,
                        password}, this.validarOperationCompleted, userState);
        }
        
        private void OnvalidarOperationCompleted(object arg) {
            if ((this.validarCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.validarCompleted(this, new validarCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.galileo.edu/obtenerTitulosxCarrera", RequestNamespace="http://www.galileo.edu", ResponseNamespace="http://www.galileo.edu", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet obtenerTitulosxCarrera(string carrera, int titulo) {
            object[] results = this.Invoke("obtenerTitulosxCarrera", new object[] {
                        carrera,
                        titulo});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void obtenerTitulosxCarreraAsync(string carrera, int titulo) {
            this.obtenerTitulosxCarreraAsync(carrera, titulo, null);
        }
        
        /// <remarks/>
        public void obtenerTitulosxCarreraAsync(string carrera, int titulo, object userState) {
            if ((this.obtenerTitulosxCarreraOperationCompleted == null)) {
                this.obtenerTitulosxCarreraOperationCompleted = new System.Threading.SendOrPostCallback(this.OnobtenerTitulosxCarreraOperationCompleted);
            }
            this.InvokeAsync("obtenerTitulosxCarrera", new object[] {
                        carrera,
                        titulo}, this.obtenerTitulosxCarreraOperationCompleted, userState);
        }
        
        private void OnobtenerTitulosxCarreraOperationCompleted(object arg) {
            if ((this.obtenerTitulosxCarreraCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.obtenerTitulosxCarreraCompleted(this, new obtenerTitulosxCarreraCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.galileo.edu/obtenerEntidadxCarrera", RequestNamespace="http://www.galileo.edu", ResponseNamespace="http://www.galileo.edu", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet obtenerEntidadxCarrera(string carrera) {
            object[] results = this.Invoke("obtenerEntidadxCarrera", new object[] {
                        carrera});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void obtenerEntidadxCarreraAsync(string carrera) {
            this.obtenerEntidadxCarreraAsync(carrera, null);
        }
        
        /// <remarks/>
        public void obtenerEntidadxCarreraAsync(string carrera, object userState) {
            if ((this.obtenerEntidadxCarreraOperationCompleted == null)) {
                this.obtenerEntidadxCarreraOperationCompleted = new System.Threading.SendOrPostCallback(this.OnobtenerEntidadxCarreraOperationCompleted);
            }
            this.InvokeAsync("obtenerEntidadxCarrera", new object[] {
                        carrera}, this.obtenerEntidadxCarreraOperationCompleted, userState);
        }
        
        private void OnobtenerEntidadxCarreraOperationCompleted(object arg) {
            if ((this.obtenerEntidadxCarreraCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.obtenerEntidadxCarreraCompleted(this, new obtenerEntidadxCarreraCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.galileo.edu/obtenerNombreAlumno", RequestNamespace="http://www.galileo.edu", ResponseNamespace="http://www.galileo.edu", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet obtenerNombreAlumno(string carnet) {
            object[] results = this.Invoke("obtenerNombreAlumno", new object[] {
                        carnet});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void obtenerNombreAlumnoAsync(string carnet) {
            this.obtenerNombreAlumnoAsync(carnet, null);
        }
        
        /// <remarks/>
        public void obtenerNombreAlumnoAsync(string carnet, object userState) {
            if ((this.obtenerNombreAlumnoOperationCompleted == null)) {
                this.obtenerNombreAlumnoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnobtenerNombreAlumnoOperationCompleted);
            }
            this.InvokeAsync("obtenerNombreAlumno", new object[] {
                        carnet}, this.obtenerNombreAlumnoOperationCompleted, userState);
        }
        
        private void OnobtenerNombreAlumnoOperationCompleted(object arg) {
            if ((this.obtenerNombreAlumnoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.obtenerNombreAlumnoCompleted(this, new obtenerNombreAlumnoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.galileo.edu/ObtenerNombreDocente", RequestNamespace="http://www.galileo.edu", ResponseNamespace="http://www.galileo.edu", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet ObtenerNombreDocente(string codpers) {
            object[] results = this.Invoke("ObtenerNombreDocente", new object[] {
                        codpers});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void ObtenerNombreDocenteAsync(string codpers) {
            this.ObtenerNombreDocenteAsync(codpers, null);
        }
        
        /// <remarks/>
        public void ObtenerNombreDocenteAsync(string codpers, object userState) {
            if ((this.ObtenerNombreDocenteOperationCompleted == null)) {
                this.ObtenerNombreDocenteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObtenerNombreDocenteOperationCompleted);
            }
            this.InvokeAsync("ObtenerNombreDocente", new object[] {
                        codpers}, this.ObtenerNombreDocenteOperationCompleted, userState);
        }
        
        private void OnObtenerNombreDocenteOperationCompleted(object arg) {
            if ((this.ObtenerNombreDocenteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ObtenerNombreDocenteCompleted(this, new ObtenerNombreDocenteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.galileo.edu/ObtenerRequisitosCarrera", RequestNamespace="http://www.galileo.edu", ResponseNamespace="http://www.galileo.edu", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet ObtenerRequisitosCarrera(string Carrera) {
            object[] results = this.Invoke("ObtenerRequisitosCarrera", new object[] {
                        Carrera});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void ObtenerRequisitosCarreraAsync(string Carrera) {
            this.ObtenerRequisitosCarreraAsync(Carrera, null);
        }
        
        /// <remarks/>
        public void ObtenerRequisitosCarreraAsync(string Carrera, object userState) {
            if ((this.ObtenerRequisitosCarreraOperationCompleted == null)) {
                this.ObtenerRequisitosCarreraOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObtenerRequisitosCarreraOperationCompleted);
            }
            this.InvokeAsync("ObtenerRequisitosCarrera", new object[] {
                        Carrera}, this.ObtenerRequisitosCarreraOperationCompleted, userState);
        }
        
        private void OnObtenerRequisitosCarreraOperationCompleted(object arg) {
            if ((this.ObtenerRequisitosCarreraCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ObtenerRequisitosCarreraCompleted(this, new ObtenerRequisitosCarreraCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.galileo.edu/ObtenerRequisitosAdmision", RequestNamespace="http://www.galileo.edu", ResponseNamespace="http://www.galileo.edu", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet ObtenerRequisitosAdmision() {
            object[] results = this.Invoke("ObtenerRequisitosAdmision", new object[0]);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void ObtenerRequisitosAdmisionAsync() {
            this.ObtenerRequisitosAdmisionAsync(null);
        }
        
        /// <remarks/>
        public void ObtenerRequisitosAdmisionAsync(object userState) {
            if ((this.ObtenerRequisitosAdmisionOperationCompleted == null)) {
                this.ObtenerRequisitosAdmisionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObtenerRequisitosAdmisionOperationCompleted);
            }
            this.InvokeAsync("ObtenerRequisitosAdmision", new object[0], this.ObtenerRequisitosAdmisionOperationCompleted, userState);
        }
        
        private void OnObtenerRequisitosAdmisionOperationCompleted(object arg) {
            if ((this.ObtenerRequisitosAdmisionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ObtenerRequisitosAdmisionCompleted(this, new ObtenerRequisitosAdmisionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.galileo.edu/ObtenerEmpleadoDynamics", RequestNamespace="http://www.galileo.edu", ResponseNamespace="http://www.galileo.edu", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet ObtenerEmpleadoDynamics(string emplid) {
            object[] results = this.Invoke("ObtenerEmpleadoDynamics", new object[] {
                        emplid});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void ObtenerEmpleadoDynamicsAsync(string emplid) {
            this.ObtenerEmpleadoDynamicsAsync(emplid, null);
        }
        
        /// <remarks/>
        public void ObtenerEmpleadoDynamicsAsync(string emplid, object userState) {
            if ((this.ObtenerEmpleadoDynamicsOperationCompleted == null)) {
                this.ObtenerEmpleadoDynamicsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObtenerEmpleadoDynamicsOperationCompleted);
            }
            this.InvokeAsync("ObtenerEmpleadoDynamics", new object[] {
                        emplid}, this.ObtenerEmpleadoDynamicsOperationCompleted, userState);
        }
        
        private void OnObtenerEmpleadoDynamicsOperationCompleted(object arg) {
            if ((this.ObtenerEmpleadoDynamicsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ObtenerEmpleadoDynamicsCompleted(this, new ObtenerEmpleadoDynamicsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.galileo.edu/ObtenerFacultades", RequestNamespace="http://www.galileo.edu", ResponseNamespace="http://www.galileo.edu", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet ObtenerFacultades() {
            object[] results = this.Invoke("ObtenerFacultades", new object[0]);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void ObtenerFacultadesAsync() {
            this.ObtenerFacultadesAsync(null);
        }
        
        /// <remarks/>
        public void ObtenerFacultadesAsync(object userState) {
            if ((this.ObtenerFacultadesOperationCompleted == null)) {
                this.ObtenerFacultadesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObtenerFacultadesOperationCompleted);
            }
            this.InvokeAsync("ObtenerFacultades", new object[0], this.ObtenerFacultadesOperationCompleted, userState);
        }
        
        private void OnObtenerFacultadesOperationCompleted(object arg) {
            if ((this.ObtenerFacultadesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ObtenerFacultadesCompleted(this, new ObtenerFacultadesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.galileo.edu/ViculosxUsuario", RequestNamespace="http://www.galileo.edu", ResponseNamespace="http://www.galileo.edu", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet ViculosxUsuario(string usuario) {
            object[] results = this.Invoke("ViculosxUsuario", new object[] {
                        usuario});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void ViculosxUsuarioAsync(string usuario) {
            this.ViculosxUsuarioAsync(usuario, null);
        }
        
        /// <remarks/>
        public void ViculosxUsuarioAsync(string usuario, object userState) {
            if ((this.ViculosxUsuarioOperationCompleted == null)) {
                this.ViculosxUsuarioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnViculosxUsuarioOperationCompleted);
            }
            this.InvokeAsync("ViculosxUsuario", new object[] {
                        usuario}, this.ViculosxUsuarioOperationCompleted, userState);
        }
        
        private void OnViculosxUsuarioOperationCompleted(object arg) {
            if ((this.ViculosxUsuarioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ViculosxUsuarioCompleted(this, new ViculosxUsuarioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.galileo.edu/SolicitudesSinTerminar", RequestNamespace="http://www.galileo.edu", ResponseNamespace="http://www.galileo.edu", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet SolicitudesSinTerminar(string carrera, string carnet, decimal tramite) {
            object[] results = this.Invoke("SolicitudesSinTerminar", new object[] {
                        carrera,
                        carnet,
                        tramite});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void SolicitudesSinTerminarAsync(string carrera, string carnet, decimal tramite) {
            this.SolicitudesSinTerminarAsync(carrera, carnet, tramite, null);
        }
        
        /// <remarks/>
        public void SolicitudesSinTerminarAsync(string carrera, string carnet, decimal tramite, object userState) {
            if ((this.SolicitudesSinTerminarOperationCompleted == null)) {
                this.SolicitudesSinTerminarOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSolicitudesSinTerminarOperationCompleted);
            }
            this.InvokeAsync("SolicitudesSinTerminar", new object[] {
                        carrera,
                        carnet,
                        tramite}, this.SolicitudesSinTerminarOperationCompleted, userState);
        }
        
        private void OnSolicitudesSinTerminarOperationCompleted(object arg) {
            if ((this.SolicitudesSinTerminarCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SolicitudesSinTerminarCompleted(this, new SolicitudesSinTerminarCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.galileo.edu")]
    public partial class Etiquetas {
        
        private short etiquetaField;
        
        private string valorField;
        
        /// <remarks/>
        public short Etiqueta {
            get {
                return this.etiquetaField;
            }
            set {
                this.etiquetaField = value;
            }
        }
        
        /// <remarks/>
        public string Valor {
            get {
                return this.valorField;
            }
            set {
                this.valorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.galileo.edu")]
    public partial class Carchivo {
        
        private byte[] contenidoField;
        
        private string mIMEField;
        
        private string nombreField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] Contenido {
            get {
                return this.contenidoField;
            }
            set {
                this.contenidoField = value;
            }
        }
        
        /// <remarks/>
        public string MIME {
            get {
                return this.mIMEField;
            }
            set {
                this.mIMEField = value;
            }
        }
        
        /// <remarks/>
        public string Nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void ObtenerGeneralCompletedEventHandler(object sender, ObtenerGeneralCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ObtenerGeneralCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ObtenerGeneralCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Carchivo Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Carchivo)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void ObtenerCompletedEventHandler(object sender, ObtenerCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ObtenerCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ObtenerCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Carchivo Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Carchivo)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void ObtenerxarchivoCompletedEventHandler(object sender, ObtenerxarchivoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ObtenerxarchivoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ObtenerxarchivoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Carchivo Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Carchivo)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void GuardarConEtiquetasCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void GuardarGeneralCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void GuardarGeneralFCompletedEventHandler(object sender, GuardarGeneralFCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GuardarGeneralFCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GuardarGeneralFCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public decimal Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((decimal)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void GuardarCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void GuardarFCompletedEventHandler(object sender, GuardarFCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GuardarFCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GuardarFCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public decimal Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((decimal)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void ObtenerCarrerasxCarnetCompletedEventHandler(object sender, ObtenerCarrerasxCarnetCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ObtenerCarrerasxCarnetCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ObtenerCarrerasxCarnetCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void ObtieneEtiquetasxArhivoCompletedEventHandler(object sender, ObtieneEtiquetasxArhivoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ObtieneEtiquetasxArhivoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ObtieneEtiquetasxArhivoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void GuardarEtiquetasCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void RemoverEtiquetasCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void ObtenerAppsCompletedEventHandler(object sender, ObtenerAppsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ObtenerAppsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ObtenerAppsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void ObtenerCatCompletedEventHandler(object sender, ObtenerCatCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ObtenerCatCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ObtenerCatCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void ObtenerEtiquetasCompletedEventHandler(object sender, ObtenerEtiquetasCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ObtenerEtiquetasCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ObtenerEtiquetasCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void ObtenerArchivosCompletedEventHandler(object sender, ObtenerArchivosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ObtenerArchivosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ObtenerArchivosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void DardebajaCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void DardebajaSolCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void AutomatizarCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void validarCompletedEventHandler(object sender, validarCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class validarCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal validarCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void obtenerTitulosxCarreraCompletedEventHandler(object sender, obtenerTitulosxCarreraCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class obtenerTitulosxCarreraCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal obtenerTitulosxCarreraCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void obtenerEntidadxCarreraCompletedEventHandler(object sender, obtenerEntidadxCarreraCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class obtenerEntidadxCarreraCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal obtenerEntidadxCarreraCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void obtenerNombreAlumnoCompletedEventHandler(object sender, obtenerNombreAlumnoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class obtenerNombreAlumnoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal obtenerNombreAlumnoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void ObtenerNombreDocenteCompletedEventHandler(object sender, ObtenerNombreDocenteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ObtenerNombreDocenteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ObtenerNombreDocenteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void ObtenerRequisitosCarreraCompletedEventHandler(object sender, ObtenerRequisitosCarreraCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ObtenerRequisitosCarreraCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ObtenerRequisitosCarreraCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void ObtenerRequisitosAdmisionCompletedEventHandler(object sender, ObtenerRequisitosAdmisionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ObtenerRequisitosAdmisionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ObtenerRequisitosAdmisionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void ObtenerEmpleadoDynamicsCompletedEventHandler(object sender, ObtenerEmpleadoDynamicsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ObtenerEmpleadoDynamicsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ObtenerEmpleadoDynamicsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void ObtenerFacultadesCompletedEventHandler(object sender, ObtenerFacultadesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ObtenerFacultadesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ObtenerFacultadesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void ViculosxUsuarioCompletedEventHandler(object sender, ViculosxUsuarioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ViculosxUsuarioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ViculosxUsuarioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void SolicitudesSinTerminarCompletedEventHandler(object sender, SolicitudesSinTerminarCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SolicitudesSinTerminarCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SolicitudesSinTerminarCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591