//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace WindowsFormsApplication1.wsPrestaciones {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="PrestacionesSoap", Namespace="http://tempuri.org/")]
    public partial class Prestaciones : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback actualizarAdministrativosOperationCompleted;
        
        private System.Threading.SendOrPostCallback actualizarDireccionOperationCompleted;
        
        private System.Threading.SendOrPostCallback cambiarFotografiaOperationCompleted;
        
        private System.Threading.SendOrPostCallback solicitarCarneOperationCompleted;
        
        private System.Threading.SendOrPostCallback BuscarDocenteOperationCompleted;
        
        private System.Threading.SendOrPostCallback ObtenerPaisesOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConsultarCorrelativoOperationCompleted;
        
        private System.Threading.SendOrPostCallback ObtenerDepartamentosOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConsultarCarnetOperationCompleted;
        
        private System.Threading.SendOrPostCallback ObtenerMunicipiosOperationCompleted;
        
        private System.Threading.SendOrPostCallback ObtenerOrdenesOperationCompleted;
        
        private System.Threading.SendOrPostCallback verificarRequisitosOperationCompleted;
        
        private System.Threading.SendOrPostCallback esSecretariaOperationCompleted;
        
        private System.Threading.SendOrPostCallback docenteActivoOperationCompleted;
        
        private System.Threading.SendOrPostCallback enviarSolicitudOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Prestaciones() {
            this.Url = global::WindowsFormsApplication1.Properties.Settings.Default.WindowsFormsApplication1_wsPrestaciones_Prestaciones;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event actualizarAdministrativosCompletedEventHandler actualizarAdministrativosCompleted;
        
        /// <remarks/>
        public event actualizarDireccionCompletedEventHandler actualizarDireccionCompleted;
        
        /// <remarks/>
        public event cambiarFotografiaCompletedEventHandler cambiarFotografiaCompleted;
        
        /// <remarks/>
        public event solicitarCarneCompletedEventHandler solicitarCarneCompleted;
        
        /// <remarks/>
        public event BuscarDocenteCompletedEventHandler BuscarDocenteCompleted;
        
        /// <remarks/>
        public event ObtenerPaisesCompletedEventHandler ObtenerPaisesCompleted;
        
        /// <remarks/>
        public event ConsultarCorrelativoCompletedEventHandler ConsultarCorrelativoCompleted;
        
        /// <remarks/>
        public event ObtenerDepartamentosCompletedEventHandler ObtenerDepartamentosCompleted;
        
        /// <remarks/>
        public event ConsultarCarnetCompletedEventHandler ConsultarCarnetCompleted;
        
        /// <remarks/>
        public event ObtenerMunicipiosCompletedEventHandler ObtenerMunicipiosCompleted;
        
        /// <remarks/>
        public event ObtenerOrdenesCompletedEventHandler ObtenerOrdenesCompleted;
        
        /// <remarks/>
        public event verificarRequisitosCompletedEventHandler verificarRequisitosCompleted;
        
        /// <remarks/>
        public event esSecretariaCompletedEventHandler esSecretariaCompleted;
        
        /// <remarks/>
        public event docenteActivoCompletedEventHandler docenteActivoCompleted;
        
        /// <remarks/>
        public event enviarSolicitudCompletedEventHandler enviarSolicitudCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/actualizarAdministrativos", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string actualizarAdministrativos(
                    string CodPers, 
                    string TipoCarnet, 
                    string Accion, 
                    string Subaccion, 
                    string Nombre1, 
                    string Nombre2, 
                    string Apellido1, 
                    string Apellido2, 
                    string NIT, 
                    string NombreImpresion, 
                    string Sexo, 
                    string EstadoCivil, 
                    System.DateTime FechaNacimiento, 
                    string IDOrden, 
                    string IDRegistro, 
                    string IDPais, 
                    string IDDepartamento, 
                    string IDMunicipio, 
                    string AdmonPuesto, 
                    string AdmonDepartamento, 
                    string Email) {
            object[] results = this.Invoke("actualizarAdministrativos", new object[] {
                        CodPers,
                        TipoCarnet,
                        Accion,
                        Subaccion,
                        Nombre1,
                        Nombre2,
                        Apellido1,
                        Apellido2,
                        NIT,
                        NombreImpresion,
                        Sexo,
                        EstadoCivil,
                        FechaNacimiento,
                        IDOrden,
                        IDRegistro,
                        IDPais,
                        IDDepartamento,
                        IDMunicipio,
                        AdmonPuesto,
                        AdmonDepartamento,
                        Email});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void actualizarAdministrativosAsync(
                    string CodPers, 
                    string TipoCarnet, 
                    string Accion, 
                    string Subaccion, 
                    string Nombre1, 
                    string Nombre2, 
                    string Apellido1, 
                    string Apellido2, 
                    string NIT, 
                    string NombreImpresion, 
                    string Sexo, 
                    string EstadoCivil, 
                    System.DateTime FechaNacimiento, 
                    string IDOrden, 
                    string IDRegistro, 
                    string IDPais, 
                    string IDDepartamento, 
                    string IDMunicipio, 
                    string AdmonPuesto, 
                    string AdmonDepartamento, 
                    string Email) {
            this.actualizarAdministrativosAsync(CodPers, TipoCarnet, Accion, Subaccion, Nombre1, Nombre2, Apellido1, Apellido2, NIT, NombreImpresion, Sexo, EstadoCivil, FechaNacimiento, IDOrden, IDRegistro, IDPais, IDDepartamento, IDMunicipio, AdmonPuesto, AdmonDepartamento, Email, null);
        }
        
        /// <remarks/>
        public void actualizarAdministrativosAsync(
                    string CodPers, 
                    string TipoCarnet, 
                    string Accion, 
                    string Subaccion, 
                    string Nombre1, 
                    string Nombre2, 
                    string Apellido1, 
                    string Apellido2, 
                    string NIT, 
                    string NombreImpresion, 
                    string Sexo, 
                    string EstadoCivil, 
                    System.DateTime FechaNacimiento, 
                    string IDOrden, 
                    string IDRegistro, 
                    string IDPais, 
                    string IDDepartamento, 
                    string IDMunicipio, 
                    string AdmonPuesto, 
                    string AdmonDepartamento, 
                    string Email, 
                    object userState) {
            if ((this.actualizarAdministrativosOperationCompleted == null)) {
                this.actualizarAdministrativosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnactualizarAdministrativosOperationCompleted);
            }
            this.InvokeAsync("actualizarAdministrativos", new object[] {
                        CodPers,
                        TipoCarnet,
                        Accion,
                        Subaccion,
                        Nombre1,
                        Nombre2,
                        Apellido1,
                        Apellido2,
                        NIT,
                        NombreImpresion,
                        Sexo,
                        EstadoCivil,
                        FechaNacimiento,
                        IDOrden,
                        IDRegistro,
                        IDPais,
                        IDDepartamento,
                        IDMunicipio,
                        AdmonPuesto,
                        AdmonDepartamento,
                        Email}, this.actualizarAdministrativosOperationCompleted, userState);
        }
        
        private void OnactualizarAdministrativosOperationCompleted(object arg) {
            if ((this.actualizarAdministrativosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.actualizarAdministrativosCompleted(this, new actualizarAdministrativosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/actualizarDireccion", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string actualizarDireccion(string CodPers, string Direccion, string Casa, string Zona, string Colonia, string Apto, string Telefono, string Departamento, string Municipio) {
            object[] results = this.Invoke("actualizarDireccion", new object[] {
                        CodPers,
                        Direccion,
                        Casa,
                        Zona,
                        Colonia,
                        Apto,
                        Telefono,
                        Departamento,
                        Municipio});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void actualizarDireccionAsync(string CodPers, string Direccion, string Casa, string Zona, string Colonia, string Apto, string Telefono, string Departamento, string Municipio) {
            this.actualizarDireccionAsync(CodPers, Direccion, Casa, Zona, Colonia, Apto, Telefono, Departamento, Municipio, null);
        }
        
        /// <remarks/>
        public void actualizarDireccionAsync(string CodPers, string Direccion, string Casa, string Zona, string Colonia, string Apto, string Telefono, string Departamento, string Municipio, object userState) {
            if ((this.actualizarDireccionOperationCompleted == null)) {
                this.actualizarDireccionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnactualizarDireccionOperationCompleted);
            }
            this.InvokeAsync("actualizarDireccion", new object[] {
                        CodPers,
                        Direccion,
                        Casa,
                        Zona,
                        Colonia,
                        Apto,
                        Telefono,
                        Departamento,
                        Municipio}, this.actualizarDireccionOperationCompleted, userState);
        }
        
        private void OnactualizarDireccionOperationCompleted(object arg) {
            if ((this.actualizarDireccionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.actualizarDireccionCompleted(this, new actualizarDireccionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/cambiarFotografia", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string cambiarFotografia([System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")] byte[] foto, string Correlativo) {
            object[] results = this.Invoke("cambiarFotografia", new object[] {
                        foto,
                        Correlativo});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void cambiarFotografiaAsync(byte[] foto, string Correlativo) {
            this.cambiarFotografiaAsync(foto, Correlativo, null);
        }
        
        /// <remarks/>
        public void cambiarFotografiaAsync(byte[] foto, string Correlativo, object userState) {
            if ((this.cambiarFotografiaOperationCompleted == null)) {
                this.cambiarFotografiaOperationCompleted = new System.Threading.SendOrPostCallback(this.OncambiarFotografiaOperationCompleted);
            }
            this.InvokeAsync("cambiarFotografia", new object[] {
                        foto,
                        Correlativo}, this.cambiarFotografiaOperationCompleted, userState);
        }
        
        private void OncambiarFotografiaOperationCompleted(object arg) {
            if ((this.cambiarFotografiaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.cambiarFotografiaCompleted(this, new cambiarFotografiaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/solicitarCarne", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string solicitarCarne(int vopcion, [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")] byte[] foto, string Correlativo) {
            object[] results = this.Invoke("solicitarCarne", new object[] {
                        vopcion,
                        foto,
                        Correlativo});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void solicitarCarneAsync(int vopcion, byte[] foto, string Correlativo) {
            this.solicitarCarneAsync(vopcion, foto, Correlativo, null);
        }
        
        /// <remarks/>
        public void solicitarCarneAsync(int vopcion, byte[] foto, string Correlativo, object userState) {
            if ((this.solicitarCarneOperationCompleted == null)) {
                this.solicitarCarneOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsolicitarCarneOperationCompleted);
            }
            this.InvokeAsync("solicitarCarne", new object[] {
                        vopcion,
                        foto,
                        Correlativo}, this.solicitarCarneOperationCompleted, userState);
        }
        
        private void OnsolicitarCarneOperationCompleted(object arg) {
            if ((this.solicitarCarneCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.solicitarCarneCompleted(this, new solicitarCarneCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/BuscarDocente", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable BuscarDocente(string Nombre) {
            object[] results = this.Invoke("BuscarDocente", new object[] {
                        Nombre});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void BuscarDocenteAsync(string Nombre) {
            this.BuscarDocenteAsync(Nombre, null);
        }
        
        /// <remarks/>
        public void BuscarDocenteAsync(string Nombre, object userState) {
            if ((this.BuscarDocenteOperationCompleted == null)) {
                this.BuscarDocenteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBuscarDocenteOperationCompleted);
            }
            this.InvokeAsync("BuscarDocente", new object[] {
                        Nombre}, this.BuscarDocenteOperationCompleted, userState);
        }
        
        private void OnBuscarDocenteOperationCompleted(object arg) {
            if ((this.BuscarDocenteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BuscarDocenteCompleted(this, new BuscarDocenteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ObtenerPaises", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable ObtenerPaises() {
            object[] results = this.Invoke("ObtenerPaises", new object[0]);
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void ObtenerPaisesAsync() {
            this.ObtenerPaisesAsync(null);
        }
        
        /// <remarks/>
        public void ObtenerPaisesAsync(object userState) {
            if ((this.ObtenerPaisesOperationCompleted == null)) {
                this.ObtenerPaisesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObtenerPaisesOperationCompleted);
            }
            this.InvokeAsync("ObtenerPaises", new object[0], this.ObtenerPaisesOperationCompleted, userState);
        }
        
        private void OnObtenerPaisesOperationCompleted(object arg) {
            if ((this.ObtenerPaisesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ObtenerPaisesCompleted(this, new ObtenerPaisesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ConsultarCorrelativo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable ConsultarCorrelativo(string Correlativo) {
            object[] results = this.Invoke("ConsultarCorrelativo", new object[] {
                        Correlativo});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void ConsultarCorrelativoAsync(string Correlativo) {
            this.ConsultarCorrelativoAsync(Correlativo, null);
        }
        
        /// <remarks/>
        public void ConsultarCorrelativoAsync(string Correlativo, object userState) {
            if ((this.ConsultarCorrelativoOperationCompleted == null)) {
                this.ConsultarCorrelativoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultarCorrelativoOperationCompleted);
            }
            this.InvokeAsync("ConsultarCorrelativo", new object[] {
                        Correlativo}, this.ConsultarCorrelativoOperationCompleted, userState);
        }
        
        private void OnConsultarCorrelativoOperationCompleted(object arg) {
            if ((this.ConsultarCorrelativoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultarCorrelativoCompleted(this, new ConsultarCorrelativoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ObtenerDepartamentos", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable ObtenerDepartamentos(string Pais) {
            object[] results = this.Invoke("ObtenerDepartamentos", new object[] {
                        Pais});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void ObtenerDepartamentosAsync(string Pais) {
            this.ObtenerDepartamentosAsync(Pais, null);
        }
        
        /// <remarks/>
        public void ObtenerDepartamentosAsync(string Pais, object userState) {
            if ((this.ObtenerDepartamentosOperationCompleted == null)) {
                this.ObtenerDepartamentosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObtenerDepartamentosOperationCompleted);
            }
            this.InvokeAsync("ObtenerDepartamentos", new object[] {
                        Pais}, this.ObtenerDepartamentosOperationCompleted, userState);
        }
        
        private void OnObtenerDepartamentosOperationCompleted(object arg) {
            if ((this.ObtenerDepartamentosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ObtenerDepartamentosCompleted(this, new ObtenerDepartamentosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ConsultarCarnet", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable ConsultarCarnet(string Carnet) {
            object[] results = this.Invoke("ConsultarCarnet", new object[] {
                        Carnet});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void ConsultarCarnetAsync(string Carnet) {
            this.ConsultarCarnetAsync(Carnet, null);
        }
        
        /// <remarks/>
        public void ConsultarCarnetAsync(string Carnet, object userState) {
            if ((this.ConsultarCarnetOperationCompleted == null)) {
                this.ConsultarCarnetOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultarCarnetOperationCompleted);
            }
            this.InvokeAsync("ConsultarCarnet", new object[] {
                        Carnet}, this.ConsultarCarnetOperationCompleted, userState);
        }
        
        private void OnConsultarCarnetOperationCompleted(object arg) {
            if ((this.ConsultarCarnetCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultarCarnetCompleted(this, new ConsultarCarnetCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ObtenerMunicipios", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable ObtenerMunicipios(string Pais, string Departamento) {
            object[] results = this.Invoke("ObtenerMunicipios", new object[] {
                        Pais,
                        Departamento});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void ObtenerMunicipiosAsync(string Pais, string Departamento) {
            this.ObtenerMunicipiosAsync(Pais, Departamento, null);
        }
        
        /// <remarks/>
        public void ObtenerMunicipiosAsync(string Pais, string Departamento, object userState) {
            if ((this.ObtenerMunicipiosOperationCompleted == null)) {
                this.ObtenerMunicipiosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObtenerMunicipiosOperationCompleted);
            }
            this.InvokeAsync("ObtenerMunicipios", new object[] {
                        Pais,
                        Departamento}, this.ObtenerMunicipiosOperationCompleted, userState);
        }
        
        private void OnObtenerMunicipiosOperationCompleted(object arg) {
            if ((this.ObtenerMunicipiosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ObtenerMunicipiosCompleted(this, new ObtenerMunicipiosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ObtenerOrdenes", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable ObtenerOrdenes(string Pais, string Departamento) {
            object[] results = this.Invoke("ObtenerOrdenes", new object[] {
                        Pais,
                        Departamento});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void ObtenerOrdenesAsync(string Pais, string Departamento) {
            this.ObtenerOrdenesAsync(Pais, Departamento, null);
        }
        
        /// <remarks/>
        public void ObtenerOrdenesAsync(string Pais, string Departamento, object userState) {
            if ((this.ObtenerOrdenesOperationCompleted == null)) {
                this.ObtenerOrdenesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObtenerOrdenesOperationCompleted);
            }
            this.InvokeAsync("ObtenerOrdenes", new object[] {
                        Pais,
                        Departamento}, this.ObtenerOrdenesOperationCompleted, userState);
        }
        
        private void OnObtenerOrdenesOperationCompleted(object arg) {
            if ((this.ObtenerOrdenesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ObtenerOrdenesCompleted(this, new ObtenerOrdenesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/verificarRequisitos", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool verificarRequisitos(string Usuario) {
            object[] results = this.Invoke("verificarRequisitos", new object[] {
                        Usuario});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void verificarRequisitosAsync(string Usuario) {
            this.verificarRequisitosAsync(Usuario, null);
        }
        
        /// <remarks/>
        public void verificarRequisitosAsync(string Usuario, object userState) {
            if ((this.verificarRequisitosOperationCompleted == null)) {
                this.verificarRequisitosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnverificarRequisitosOperationCompleted);
            }
            this.InvokeAsync("verificarRequisitos", new object[] {
                        Usuario}, this.verificarRequisitosOperationCompleted, userState);
        }
        
        private void OnverificarRequisitosOperationCompleted(object arg) {
            if ((this.verificarRequisitosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.verificarRequisitosCompleted(this, new verificarRequisitosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/esSecretaria", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool esSecretaria(string Usuario, string Carnet) {
            object[] results = this.Invoke("esSecretaria", new object[] {
                        Usuario,
                        Carnet});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void esSecretariaAsync(string Usuario, string Carnet) {
            this.esSecretariaAsync(Usuario, Carnet, null);
        }
        
        /// <remarks/>
        public void esSecretariaAsync(string Usuario, string Carnet, object userState) {
            if ((this.esSecretariaOperationCompleted == null)) {
                this.esSecretariaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnesSecretariaOperationCompleted);
            }
            this.InvokeAsync("esSecretaria", new object[] {
                        Usuario,
                        Carnet}, this.esSecretariaOperationCompleted, userState);
        }
        
        private void OnesSecretariaOperationCompleted(object arg) {
            if ((this.esSecretariaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.esSecretariaCompleted(this, new esSecretariaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/docenteActivo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool docenteActivo(string Correlativo) {
            object[] results = this.Invoke("docenteActivo", new object[] {
                        Correlativo});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void docenteActivoAsync(string Correlativo) {
            this.docenteActivoAsync(Correlativo, null);
        }
        
        /// <remarks/>
        public void docenteActivoAsync(string Correlativo, object userState) {
            if ((this.docenteActivoOperationCompleted == null)) {
                this.docenteActivoOperationCompleted = new System.Threading.SendOrPostCallback(this.OndocenteActivoOperationCompleted);
            }
            this.InvokeAsync("docenteActivo", new object[] {
                        Correlativo}, this.docenteActivoOperationCompleted, userState);
        }
        
        private void OndocenteActivoOperationCompleted(object arg) {
            if ((this.docenteActivoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.docenteActivoCompleted(this, new docenteActivoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/enviarSolicitud", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string enviarSolicitud(string carrera, string carnet, string comentarios, int tramite, string Usuario, string Aplicacion) {
            object[] results = this.Invoke("enviarSolicitud", new object[] {
                        carrera,
                        carnet,
                        comentarios,
                        tramite,
                        Usuario,
                        Aplicacion});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void enviarSolicitudAsync(string carrera, string carnet, string comentarios, int tramite, string Usuario, string Aplicacion) {
            this.enviarSolicitudAsync(carrera, carnet, comentarios, tramite, Usuario, Aplicacion, null);
        }
        
        /// <remarks/>
        public void enviarSolicitudAsync(string carrera, string carnet, string comentarios, int tramite, string Usuario, string Aplicacion, object userState) {
            if ((this.enviarSolicitudOperationCompleted == null)) {
                this.enviarSolicitudOperationCompleted = new System.Threading.SendOrPostCallback(this.OnenviarSolicitudOperationCompleted);
            }
            this.InvokeAsync("enviarSolicitud", new object[] {
                        carrera,
                        carnet,
                        comentarios,
                        tramite,
                        Usuario,
                        Aplicacion}, this.enviarSolicitudOperationCompleted, userState);
        }
        
        private void OnenviarSolicitudOperationCompleted(object arg) {
            if ((this.enviarSolicitudCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.enviarSolicitudCompleted(this, new enviarSolicitudCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void actualizarAdministrativosCompletedEventHandler(object sender, actualizarAdministrativosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class actualizarAdministrativosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal actualizarAdministrativosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void actualizarDireccionCompletedEventHandler(object sender, actualizarDireccionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class actualizarDireccionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal actualizarDireccionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void cambiarFotografiaCompletedEventHandler(object sender, cambiarFotografiaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class cambiarFotografiaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal cambiarFotografiaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void solicitarCarneCompletedEventHandler(object sender, solicitarCarneCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class solicitarCarneCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal solicitarCarneCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void BuscarDocenteCompletedEventHandler(object sender, BuscarDocenteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BuscarDocenteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BuscarDocenteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void ObtenerPaisesCompletedEventHandler(object sender, ObtenerPaisesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ObtenerPaisesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ObtenerPaisesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void ConsultarCorrelativoCompletedEventHandler(object sender, ConsultarCorrelativoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultarCorrelativoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsultarCorrelativoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void ObtenerDepartamentosCompletedEventHandler(object sender, ObtenerDepartamentosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ObtenerDepartamentosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ObtenerDepartamentosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void ConsultarCarnetCompletedEventHandler(object sender, ConsultarCarnetCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultarCarnetCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsultarCarnetCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void ObtenerMunicipiosCompletedEventHandler(object sender, ObtenerMunicipiosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ObtenerMunicipiosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ObtenerMunicipiosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void ObtenerOrdenesCompletedEventHandler(object sender, ObtenerOrdenesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ObtenerOrdenesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ObtenerOrdenesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void verificarRequisitosCompletedEventHandler(object sender, verificarRequisitosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class verificarRequisitosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal verificarRequisitosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void esSecretariaCompletedEventHandler(object sender, esSecretariaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class esSecretariaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal esSecretariaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void docenteActivoCompletedEventHandler(object sender, docenteActivoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class docenteActivoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal docenteActivoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void enviarSolicitudCompletedEventHandler(object sender, enviarSolicitudCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class enviarSolicitudCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal enviarSolicitudCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591